##
# Created by Supun Kanushka
# Copyright (c) 2018, All Rights Reserved.
#
version: '3'

services:
  php:
    build: './php/'
    links:
    - mysql:mysql
    volumes:
    - ./php-app/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
    - php
    - mysql
    links:
    - php:php
    - mysql:mysql
    ports:
    - "8080:80"
    volumes:
    - ./php-app/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    environment:
    - MYSQL_ROOT_PASSWORD=sample
networks:
  frontend:
  backend: